### ISSUE TITLE
HTML rendering renders too much whitespace

### ISSUE THREAD

**Issue by mbaltus** [FirelyTeam/spark#79] opened 2016-04-18 10:59 UTC
When requesting a resource through a browser, the HTML renderer adds whitespace before each value.
For example:

`<status value=" generated" />`

**Comment by brianpos** [comment] 2016-04-18 11:20
I have this fixed already, just need to commit it. Just a change to the stylesheet.

**Comment by mbaltus** [comment] 2016-04-18 11:22
Thanks, can you close this issue when the commit is done?

**Comment by gtakov** [comment] 2016-05-25 14:31
Could you please provide feedback if you will have time to commit in the following period (the issue is assigned to the milestone Baltimore which is due by September 16, 2016)? As far as I can see it is still not resolved. Thanks in advance.

**Closed** 2019-11-12 07:38 UTC
